//! Generated-image backup, restart, and active-lifecycle recovery tests.

use std::fs;

use image::{ImageFormat, Rgba, RgbaImage};
use rusqlite::Connection;

use super::{tests::test_database_path, *};

/// Appends one durable image prompt and returns its request plus exact provenance.
fn generated_request(
    store: &ConversationStore,
    conversation: &StoredConversation,
) -> (StoredMessage, GeneratedImageProvenance) {
    let request = store
        .append_message(NewStoredMessage {
            conversation_id: conversation.id.clone(),
            role: StoredRole::User,
            text: "A portable generated square".into(),
            reasoning: None,
            state: MessageState::Final,
            provider_id: None,
            model_id: None,
        })
        .expect("prompt should persist");
    let provenance = GeneratedImageProvenance::new(
        "qwen-image",
        "qwen-image-2.0-2026-03-03",
        GeneratedAssetExecution::Cloud,
        Some(7),
    )
    .expect("provenance should be valid");
    (request, provenance)
}

/// Starts one generated-image response with the shared bounded request options.
fn start_generated(
    store: &ConversationStore,
    conversation: &StoredConversation,
    output_count: u8,
) -> StoredMessage {
    let (request, provenance) = generated_request(store, conversation);
    let options =
        GeneratedImageRequestOptions::new(1_024, 1_024, false).expect("options should be valid");
    store
        .start_generated_image_message(
            &conversation.id,
            &request.id,
            &request.text,
            output_count,
            &provenance,
            &options,
        )
        .expect("generation should start")
        .message
}

/// Creates one completed generated PNG beside a recovery fixture.
fn complete_generated(
    store: &ConversationStore,
    conversation: &StoredConversation,
) -> StoredGeneratedAsset {
    let pending = start_generated(store, conversation, 1);
    let directory = store.generated_asset_temporary_directory();
    fs::create_dir_all(&directory).expect("generated temporary directory should exist");
    let path = directory.join(format!("{}.png.part", uuid::Uuid::new_v4()));
    RgbaImage::from_pixel(2, 2, Rgba([127, 127, 127, 255]))
        .save_with_format(&path, ImageFormat::Png)
        .expect("generated PNG fixture should be written");
    let prepared = PreparedGeneratedImage::from_validated_png(path, 2, 2)
        .expect("generated PNG should prepare");
    store
        .complete_generated_image_message(&pending.id, &[prepared])
        .expect("generation should complete")
        .generated_assets
        .into_iter()
        .next()
        .expect("completed asset should exist")
}

#[test]
fn embeds_and_restores_verified_generated_asset_bytes() {
    let live_path = test_database_path();
    let backup_path = live_path.with_file_name("generated-portable-backup.sqlite3");
    let safety_path = live_path.with_file_name("generated-pre-restore.sqlite3");
    let live = ConversationStore::initialize(live_path).expect("live storage should initialize");
    let source_path = live
        .path
        .with_file_name("generated-backup-source")
        .join("bottie.sqlite3");
    let source = ConversationStore::initialize(source_path).expect("source should initialize");
    let conversation = source
        .create_conversation("Generated backup")
        .expect("conversation should be created");
    let generated = complete_generated(&source, &conversation);
    let sha256 = generated
        .sha256
        .expect("completed hash should exist natively");
    let expected = fs::read(
        source
            .generated_asset_blob_path(&sha256)
            .expect("source generated path should resolve"),
    )
    .expect("source generated bytes should exist");

    source
        .backup_to(&backup_path)
        .expect("generated portable backup should complete");
    let backup = Connection::open(&backup_path).expect("backup should open");
    let embedded: Vec<u8> = backup
        .query_row(
            "SELECT content FROM bottie_portable_generated_asset_blobs WHERE sha256 = ?1",
            [&sha256],
            |row| row.get(0),
        )
        .expect("generated bytes should be embedded");
    let manifest_version: i64 = backup
        .query_row("SELECT version FROM bottie_portable_manifest", [], |row| {
            row.get(0)
        })
        .expect("portable version should exist");
    drop(backup);

    live.restore_from(&backup_path, &safety_path)
        .expect("generated portable backup should restore");
    let restored = live
        .load_conversation(&conversation.id)
        .expect("restored conversation should load");
    let restored_sha = restored.messages[1].generated_assets[0]
        .sha256
        .as_deref()
        .expect("restored generated hash should exist natively");

    assert_eq!(manifest_version, 2);
    assert_eq!(embedded, expected);
    assert_eq!(restored_sha, sha256);
    assert_eq!(
        fs::read(
            live.generated_asset_blob_path(restored_sha)
                .expect("restored generated path should resolve")
        )
        .expect("restored generated bytes should exist"),
        expected
    );
}

#[test]
fn rejects_tampered_generated_asset_payload_without_changing_live_state() {
    let live_path = test_database_path();
    let backup_path = live_path.with_file_name("tampered-generated-backup.sqlite3");
    let safety_path = live_path.with_file_name("unused-generated-safety.sqlite3");
    let live = ConversationStore::initialize(live_path).expect("live storage should initialize");
    let original = live
        .create_conversation("Keep live generated state")
        .expect("live conversation should be created");
    let source_path = live
        .path
        .with_file_name("tampered-generated-source")
        .join("bottie.sqlite3");
    let source = ConversationStore::initialize(source_path).expect("source should initialize");
    let conversation = source
        .create_conversation("Tampered generated backup")
        .expect("source conversation should be created");
    complete_generated(&source, &conversation);
    source
        .backup_to(&backup_path)
        .expect("backup should complete");
    Connection::open(&backup_path)
        .expect("backup should open")
        .execute(
            "UPDATE bottie_portable_generated_asset_blobs SET content = X'00'",
            [],
        )
        .expect("generated payload should be tampered");

    let error = live
        .restore_from(&backup_path, &safety_path)
        .expect_err("tampered generated bytes must be rejected");

    assert_eq!(error.code, "invalid_request");
    assert_eq!(
        live.list_conversations()
            .expect("live conversations should list")[0]
            .id,
        original.id
    );
    assert!(!safety_path.exists());
}

#[test]
fn restart_recovers_pending_images_as_retryable_interrupted_failures() {
    let path = test_database_path();
    let store = ConversationStore::initialize(path.clone()).expect("storage should initialize");
    let conversation = store
        .create_conversation("Interrupted image")
        .expect("conversation should be created");
    let pending = start_generated(&store, &conversation, 2);
    drop(store);

    let reopened = ConversationStore::initialize(path).expect("storage should reopen");
    let recovered = reopened
        .load_conversation(&conversation.id)
        .expect("conversation should reload");
    let message = &recovered.messages[1];

    assert_eq!(message.id, pending.id);
    assert_eq!(message.state, MessageState::Failed);
    assert_eq!(message.text, "Image generation interrupted.");
    assert!(message.generated_assets.iter().all(|asset| {
        asset.status == GeneratedAssetStatus::Failed
            && asset.error_code.as_deref() == Some("interrupted")
            && asset.sha256.is_none()
    }));
    let retry = reopened
        .retry_generated_image_message(&message.id)
        .expect("interrupted generation should be retryable");
    assert_eq!(retry.prompt, "A portable generated square");
    assert_eq!(retry.output_count, 2);
}

#[test]
fn pending_image_generation_blocks_conversation_and_branch_mutation() {
    let store =
        ConversationStore::initialize(test_database_path()).expect("storage should initialize");
    let conversation = store
        .create_conversation("Active generated image")
        .expect("conversation should be created");
    let pending = start_generated(&store, &conversation, 1);
    let request = store
        .load_conversation(&conversation.id)
        .expect("conversation should load")
        .messages[0]
        .clone();

    assert!(
        store
            .append_message(NewStoredMessage {
                conversation_id: conversation.id.clone(),
                role: StoredRole::User,
                text: "Do not race the image".into(),
                reasoning: None,
                state: MessageState::Final,
                provider_id: None,
                model_id: None,
            })
            .is_err()
    );
    assert!(
        store
            .set_conversation_archived(&conversation.id, true)
            .is_err()
    );
    assert!(store.delete_conversation(&conversation.id).is_err());
    assert!(
        store
            .fork_from_user_message(&conversation.id, &request.id, "Do not fork yet")
            .is_err()
    );

    store
        .fail_generated_image_message(&pending.id, GeneratedAssetStatus::Cancelled, None)
        .expect("cancellation should release lifecycle mutation");
    assert!(
        store
            .set_conversation_archived(&conversation.id, true)
            .is_ok()
    );
}
